### PR TITLE
Update sbt to version 1.0.4

### PR DESCRIPTION
**Pull request by marcospereira**
Submitted against branch `sbt1.0.2` because looks like it is the most updated.

### CODE REVIEW

**Comment by aaccioly** [comment]
Hi @marcospereira. SBT is not listing version 1.0.4 in their download page. Having said that, there is a new version 1.1.0: https://www.scala-sbt.org/download.html

**Comment by marcospereira** [comment]
Hey @aaccioly,

The file is still there though. So maybe it is just a small glitch on the download page? I was looking at [sbt releases at github](https://github.com/sbt/sbt/releases) and not the website.

About 1.1.0, I think it should be updated in another PR (I can open a new one), but I still think it is valid to have 1.0.4 merged and released so that users can install this specific version if they want/need.

**Comment by dwijnand** [comment]
Yep, just a mistake in releasing sbt 1.1.0. Rectifying https://github.com/sbt/website/pull/579.

**Comment by aaccioly** [comment]
Hi @marcospereira and @dwijnand. Brilliant, thanks!

**Comment by dwijnand** [comment]
superseded by https://github.com/ssteward54/chocolatey-sbt/pull/8 (sbt 1.1.2)

**Pull request closed without merging**
